# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdc7f73b28db2b6ccc01e65d41960808c9610d84c1f3afbae4f8d67f45fadda53c53b1c2a35c082a53352e6d11451ecbb1b380a72a6db3a8a84d009259363bef

test:
  secret_key_base: 864f8476654023c9e5273c058dfa2977e59b4cfd671178ed54820870f46af2116211d8d246de9b554ec07bdd74526ebb5fe447d794cd7dba11167e67be5aaaa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
